const memoryCards = [
   {
      id: "ff1f1d63-e5e1-4d64-93ee-bf743765831e",
      imagery: "Container Row Column",
      answer: "Bootstrap order",
      userId: "e7cb9ca6-23e5-428f-a801-885e00720b3b",
      createdAt: Number,
      nextAttemptAt: Number,
      lastAttemptAt: Number,
      totalSuccessfulAttempts: Number,
      level: 1,
   },
   {
      id: "91eb065a-a38b-495a-a01e-ac09336ee52e",
      imagery: String,
      answer: String,
      userId: String,
      createdAt: Number,
      nextAttemptAt: Number,
      lastAttemptAt: Number,
      totalSuccessfulAttempts: Number,
      level: 1,
   },
   {
      id: "1e013b11-dc69-42b4-b491-b564fc3b38e2",
      imagery: String,
      answer: String,
      userId: String,
      createdAt: Number,
      nextAttemptAt: Number,
      lastAttemptAt: Number,
      totalSuccessfulAttempts: Number,
      level: 1,
   },
   {
      id: "55e234f5-c85a-4dcd-884d-efba04da53e4",
      imagery: String,
      answer: String,
      userId: String,
      createdAt: Number,
      nextAttemptAt: Number,
      lastAttemptAt: Number,
      totalSuccessfulAttempts: Number,
      level: 1,
   },
];
